
-- 1. What are the details of all cars purchased in the year 2022?
select 
	c.car_id 
    , c.make 
    , c.type
    , c.style 
    , c.cost 
    , s.purchase_date
from cars as c
left join sales as s
on c.car_id = s.car_id
where extract(year from s.purchase_date) = 2022;

-- 2. What is the total number of cars sold by each salesperson?
select sp.name 
	, count(s.salesman_id) as total_cars
from salespersons as sp
left join sales as s
on sp.salesman_id = s.salesman_id
group by sp.name;

-- 3. What is the total revenue generated by each salesperson?
select 
		sp.name 
        , sum(c.cost) as total_revenue
from cars as c
	left join sales as s
		on s.car_id = c.car_id
	left join salespersons as sp
		on sp.salesman_id = s.salesman_id
group by sp.name;

-- 4. What are the details of the cars sold by each salesperson?
select 
	sp.salesman_id
    , sp.name
    , s.sale_id
    , s.purchase_date
	, s.car_id
    , c.type
    , c.make
    , c.style
    , c.cost
from sales as s
left join cars as c
on s.car_id = c.car_id
left join salespersons as sp
on sp.salesman_id = s.salesman_id
order by sp.salesman_id;

-- 5. What is the total revenue generated by each car type?
select c.type
	, sum(c.cost) 
from cars as c
left join sales as s
on c.car_id= s.car_id
group by c.type
order by sum(c.cost) desc;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
select 
    c.car_id 
    , c.type
    , c.make
    , c.style
    , s.purchase_date
    , c.cost
from 
	cars as c
	left join sales as s
		on c.car_id = s.car_id
	left join salespersons as sp
		on s.salesman_id = sp.salesman_id
where 
	extract(year from s.purchase_date) = 2021 and sp.name = 'Emily Wong'
order by c.car_id;

-- 7. What is the total revenue generated by the sales of hatchback cars?
select c.style , sum(c.cost) as total_revenue
from 
	cars as c
    left join sales as s
		on c.car_id = s.car_id
where c.style = 'Hatchback'
order by c.style;

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select c.style , sum(c.cost) as total_revenue
from 
	cars as c
    left join sales as s
		on c.car_id = s.car_id
where c.style = 'SUV' and year(s.purchase_date)= 2022
order by c.style;

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select 
     sp.city
from 
	sales as s
    left join salespersons as sp
		on s.salesman_id = sp.salesman_id
where year(s.purchase_date) = 2023
group by sp.city
order by count(s.sale_id) desc
limit 1 ;

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
select 
		sp.name 
        , sp.age
from cars as c
	left join sales as s
		on s.car_id = c.car_id
	left join salespersons as sp
		on sp.salesman_id = s.salesman_id
where year(s.purchase_date)=2022
group by sp.name , sp.age
order by sum(c.cost) desc
limit 1;
